import { Account, Category, Goal, RecurringBill, Transaction } from '../types/finance';

export const INITIAL_CATEGORIES: Category[] = [
  // Despesas
  { id: 'cat-alimentacao', name: 'Alimentação & Mercado', type: 'expense', icon: 'Utensils', color: '#f97316', monthlyBudget: 1600 },
  { id: 'cat-moradia', name: 'Moradia & Contas', type: 'expense', icon: 'Home', color: '#3b82f6', monthlyBudget: 2800 },
  { id: 'cat-transporte', name: 'Transporte & Combustível', type: 'expense', icon: 'Car', color: '#eab308', monthlyBudget: 650 },
  { id: 'cat-lazer', name: 'Lazer & Restaurantes', type: 'expense', icon: 'Coffee', color: '#ec4899', monthlyBudget: 750 },
  { id: 'cat-saude', name: 'Saúde & Cuidados', type: 'expense', icon: 'HeartPulse', color: '#ef4444', monthlyBudget: 400 },
  { id: 'cat-educacao', name: 'Educação & Cursos', type: 'expense', icon: 'GraduationCap', color: '#8b5cf6', monthlyBudget: 350 },
  { id: 'cat-assinaturas', name: 'Assinaturas & Serviços', type: 'expense', icon: 'Tv', color: '#06b6d4', monthlyBudget: 220 },
  { id: 'cat-compras', name: 'Compras & Vestuário', type: 'expense', icon: 'ShoppingBag', color: '#10b981', monthlyBudget: 600 },
  { id: 'cat-outros-desp', name: 'Outras Despesas', type: 'expense', icon: 'MoreHorizontal', color: '#64748b', monthlyBudget: 300 },
  
  // Receitas
  { id: 'cat-salario', name: 'Salário Principal', type: 'income', icon: 'Briefcase', color: '#10b981' },
  { id: 'cat-freelance', name: 'Freelance & Projetos', type: 'income', icon: 'Laptop', color: '#06b6d4' },
  { id: 'cat-investimentos', name: 'Rendimentos & Dividendos', type: 'income', icon: 'TrendingUp', color: '#3b82f6' },
  { id: 'cat-outras-rec', name: 'Outras Receitas', type: 'income', icon: 'Gift', color: '#8b5cf6' },
];

export const INITIAL_ACCOUNTS: Account[] = [
  {
    id: 'acc-nubank',
    name: 'Nubank Conta Corrente',
    type: 'checking',
    institution: 'Nubank',
    initialBalance: 4820.50,
    currentBalance: 4820.50,
    color: '#8b5cf6',
  },
  {
    id: 'acc-cartao-nubank',
    name: 'Cartão de Crédito Roxinho',
    type: 'credit',
    institution: 'Nubank',
    initialBalance: 0,
    currentBalance: -2140.80,
    creditLimit: 8500.00,
    closingDay: 28,
    dueDay: 5,
    color: '#a855f7',
  },
  {
    id: 'acc-itau',
    name: 'Itaú Unibanco',
    type: 'checking',
    institution: 'Itaú',
    initialBalance: 1450.00,
    currentBalance: 1450.00,
    color: '#f97316',
  },
  {
    id: 'acc-xp',
    name: 'XP Investimentos',
    type: 'investment',
    institution: 'XP',
    initialBalance: 38450.00,
    currentBalance: 38450.00,
    color: '#3b82f6',
  },
  {
    id: 'acc-dinheiro',
    name: 'Carteira Física',
    type: 'cash',
    institution: 'Espécie',
    initialBalance: 320.00,
    currentBalance: 320.00,
    color: '#10b981',
  },
];

export const INITIAL_GOALS: Goal[] = [
  {
    id: 'goal-1',
    title: 'Reserva de Emergência (6 meses)',
    targetAmount: 30000,
    currentAmount: 24500,
    deadline: '2026-12-31',
    category: 'Segurança',
    color: '#10b981',
    icon: 'ShieldCheck',
    notes: 'Alocado em Tesouro Selic e CDB liquidez diária 100% CDI',
  },
  {
    id: 'goal-2',
    title: 'Viagem de Férias para a Praia',
    targetAmount: 7500,
    currentAmount: 5150,
    deadline: '2027-01-15',
    category: 'Lazer',
    color: '#06b6d4',
    icon: 'Palmtree',
    notes: 'Passagens e hospedagem em Florianópolis',
  },
  {
    id: 'goal-3',
    title: 'Novo Setup de Trabalho / Mac',
    targetAmount: 11000,
    currentAmount: 6800,
    deadline: '2026-11-30',
    category: 'Carreira',
    color: '#8b5cf6',
    icon: 'Laptop',
    notes: 'Equipamento para desenvolvimento e projetos freelance',
  },
];

export const INITIAL_RECURRING: RecurringBill[] = [
  {
    id: 'rec-1',
    title: 'Aluguel do Apartamento',
    amount: 2200,
    type: 'expense',
    dueDay: 10,
    category: 'cat-moradia',
    accountId: 'acc-nubank',
    isAutoPaid: true,
    lastPaidMonth: '2026-09',
  },
  {
    id: 'rec-2',
    title: 'Condomínio Residencial',
    amount: 480,
    type: 'expense',
    dueDay: 15,
    category: 'cat-moradia',
    accountId: 'acc-nubank',
    isAutoPaid: false,
    lastPaidMonth: '2026-09',
  },
  {
    id: 'rec-3',
    title: 'Internet Fibra 600MB',
    amount: 129.90,
    type: 'expense',
    dueDay: 20,
    category: 'cat-assinaturas',
    accountId: 'acc-nubank',
    isAutoPaid: true,
    lastPaidMonth: '2026-09',
  },
  {
    id: 'rec-4',
    title: 'Streaming (Netflix + Spotify)',
    amount: 86.80,
    type: 'expense',
    dueDay: 5,
    category: 'cat-assinaturas',
    accountId: 'acc-cartao-nubank',
    isAutoPaid: true,
    lastPaidMonth: '2026-10',
  },
  {
    id: 'rec-5',
    title: 'Salário Mensal CLT',
    amount: 8200,
    type: 'income',
    dueDay: 5,
    category: 'cat-salario',
    accountId: 'acc-itau',
    isAutoPaid: true,
    lastPaidMonth: '2026-10',
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-001',
    type: 'income',
    amount: 8200.00,
    date: '2026-10-05',
    description: 'Salário Mensal Líquido',
    category: 'cat-salario',
    accountId: 'acc-itau',
    status: 'completed',
    paymentMethod: 'transfer',
    tags: ['Salário', 'Empresa'],
  },
  {
    id: 'tx-002',
    type: 'expense',
    amount: 86.80,
    date: '2026-10-05',
    description: 'Netflix & Spotify Family',
    category: 'cat-assinaturas',
    accountId: 'acc-cartao-nubank',
    status: 'completed',
    paymentMethod: 'credit_card',
    tags: ['Streaming', 'Recorrente'],
  },
  {
    id: 'tx-003',
    type: 'expense',
    amount: 342.50,
    date: '2026-10-04',
    description: 'Supermercado Pão de Açúcar',
    category: 'cat-alimentacao',
    accountId: 'acc-cartao-nubank',
    status: 'completed',
    paymentMethod: 'credit_card',
    tags: ['Mercado', 'Compras do mês'],
  },
  {
    id: 'tx-004',
    type: 'expense',
    amount: 180.00,
    date: '2026-10-03',
    description: 'Abastecimento Posto Ipiranga',
    category: 'cat-transporte',
    accountId: 'acc-nubank',
    status: 'completed',
    paymentMethod: 'pix',
    tags: ['Gasolina', 'Carro'],
  },
  {
    id: 'tx-005',
    type: 'income',
    amount: 1450.00,
    date: '2026-10-02',
    description: 'Freelance Landing Page Web',
    category: 'cat-freelance',
    accountId: 'acc-nubank',
    status: 'completed',
    paymentMethod: 'pix',
    tags: ['Freela', 'Design'],
  },
  {
    id: 'tx-006',
    type: 'expense',
    amount: 125.00,
    date: '2026-10-02',
    description: 'Jantar Restaurante Japonês',
    category: 'cat-lazer',
    accountId: 'acc-cartao-nubank',
    status: 'completed',
    paymentMethod: 'credit_card',
    tags: ['Restaurante', 'Fim de semana'],
  },
  {
    id: 'tx-007',
    type: 'expense',
    amount: 78.40,
    date: '2026-10-01',
    description: 'Farmácia Droga Raia',
    category: 'cat-saude',
    accountId: 'acc-nubank',
    status: 'completed',
    paymentMethod: 'pix',
    tags: ['Medicamentos'],
  },
  {
    id: 'tx-008',
    type: 'expense',
    amount: 2200.00,
    date: '2026-10-10',
    description: 'Aluguel do Apartamento',
    category: 'cat-moradia',
    accountId: 'acc-nubank',
    status: 'pending',
    paymentMethod: 'boleto',
    tags: ['Aluguel', 'Moradia'],
    isRecurring: true,
  },
  {
    id: 'tx-009',
    type: 'expense',
    amount: 480.00,
    date: '2026-10-15',
    description: 'Condomínio Residencial',
    category: 'cat-moradia',
    accountId: 'acc-nubank',
    status: 'pending',
    paymentMethod: 'boleto',
    tags: ['Condomínio'],
    isRecurring: true,
  },
  {
    id: 'tx-010',
    type: 'expense',
    amount: 129.90,
    date: '2026-10-20',
    description: 'Internet Fibra Óptica 600MB',
    category: 'cat-assinaturas',
    accountId: 'acc-nubank',
    status: 'pending',
    paymentMethod: 'pix',
    tags: ['Internet'],
    isRecurring: true,
  },
  {
    id: 'tx-011',
    type: 'expense',
    amount: 215.00,
    date: '2026-09-29',
    description: 'Feira Orgânica & Hortifruti',
    category: 'cat-alimentacao',
    accountId: 'acc-dinheiro',
    status: 'completed',
    paymentMethod: 'cash',
    tags: ['Feira', 'Alimentação'],
  },
  {
    id: 'tx-012',
    type: 'income',
    amount: 320.40,
    date: '2026-09-28',
    description: 'Dividendos FIIs MXRF11 / HGLG11',
    category: 'cat-investimentos',
    accountId: 'acc-xp',
    status: 'completed',
    paymentMethod: 'transfer',
    tags: ['FIIs', 'Dividendos'],
  },
  {
    id: 'tx-013',
    type: 'expense',
    amount: 189.90,
    date: '2026-09-25',
    description: 'Livros de Finanças e Tecnologia',
    category: 'cat-educacao',
    accountId: 'acc-cartao-nubank',
    status: 'completed',
    paymentMethod: 'credit_card',
    tags: ['Livros', 'Estudos'],
  },
  {
    id: 'tx-014',
    type: 'expense',
    amount: 299.00,
    date: '2026-09-20',
    description: 'Tênis de Corrida (Parcela 1/3)',
    category: 'cat-compras',
    accountId: 'acc-cartao-nubank',
    status: 'completed',
    paymentMethod: 'credit_card',
    installments: { current: 1, total: 3 },
    tags: ['Vestuário', 'Esporte'],
  },
  {
    id: 'tx-015',
    type: 'expense',
    amount: 2200.00,
    date: '2026-09-10',
    description: 'Aluguel do Apartamento',
    category: 'cat-moradia',
    accountId: 'acc-nubank',
    status: 'completed',
    paymentMethod: 'boleto',
    tags: ['Aluguel'],
    isRecurring: true,
  },
  {
    id: 'tx-016',
    type: 'income',
    amount: 8200.00,
    date: '2026-09-05',
    description: 'Salário Mensal Líquido',
    category: 'cat-salario',
    accountId: 'acc-itau',
    status: 'completed',
    paymentMethod: 'transfer',
    tags: ['Salário'],
  },
];
